spring.application.name=dronelog

# TODO: conferir o banco usado na sua máquina antes de executar.
spring.datasource.url=jdbc:postgresql://localhost:5432/dronelog
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
